[package]
name = "WiiDevEnv"
version = "0.1.0"
edition = "2021"

[lib]
name = "game"
crate-type = ["staticlib"]
path = "source/game/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.61.0"
regex = "1.5"

[dependencies]
libc = "0.2"
