version: "3.9"
services:
  build_watch:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bin:/project/bin
      - ./target:/project/target
      - ./data:/project/data
      - ./src:/project/src
