version: "3.9"
services:
  builder:
    build:
      context: ./docker/builder
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./bin:/build/bin
  # emulator:
  #   image: 'andrewmackrodt/dolphin-emu-x11:5.0-r2002292233'
  #   depends_on:
  #     - builder
  #   network_mode: "host"
  #   shm_size: '128M'
  #   devices:
  #     - "/dev/input:/dev/input"
  #     - "/dev/snd:/dev/snd"
  #   volumes:
  #     - ./bin:/wii:ro