version: "3.9"
services:
  builder:
    build:
      context: ./docker/builder
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./.cargo_build_cache:/root/.cargo/registry
      - ./bin:/build/bin
