version: "3.9"
services:
  builder:
    build:
      context: ./docker/builder
      dockerfile: Dockerfile
    volumes:
      - ./app:/app # source code input
      - ./bin:/build/bin # compiled result output
      - ./.cargo_build_cache:/usr/local/cargo/registry # Cache Rust dependencies
