[package]
name = "physicslib"
version = "0.1.0"
edition = "2021"

[lib]
name="physicslib"

[dependencies]
libc = "0.2"
typed-arena = { version = "2.0.2", default-features = false }

[build-dependencies]
bindgen = "0.61"
regex = "1.5"